# Generated by Django 5.2.7 on 2025-10-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='Ativo',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='Avanco_da_OS',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='Duracao_Minutos',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='Plano_de_Tarefas',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='Responsavel',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='Tipo_de_Tarefa',
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarefa_api', models.IntegerField(unique=True, verbose_name='ID da Tarefa na API')),
                ('Ativo', models.TextField(blank=True, null=True, verbose_name='Ativo')),
                ('Responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('Plano_de_Tarefas', models.TextField(blank=True, null=True, verbose_name='Plano de Tarefas')),
                ('Tipo_de_Tarefa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Tarefa')),
                ('Duracao_Minutos', models.FloatField(blank=True, null=True, verbose_name='Duração (Minutos)')),
                ('Avanco_da_OS', models.IntegerField(blank=True, null=True, verbose_name='Avanço da OS (%)')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='Relatorio.ordemdeservico')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
