# Generated by Django 5.2.7 on 2025-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0004_remove_tarefa_avanco_da_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='Ano_Inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Data_Iniciou_OS',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Iniciou OS'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Dia_Inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Hora_Inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Mes_Inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
