# Generated by Django 5.2.7 on 2025-10-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0009_remove_tarefa_observacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='Observacao',
            new_name='Observacao_OS',
        ),
    ]
