# Generated by Django 5.2.7 on 2025-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0010_rename_observacao_ordemdeservico_observacao_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='Data_Enviado_Verificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Enviado Verificação'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Data_Programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Programada'),
        ),
    ]
