# Generated by Django 5.0.7 on 2025-10-17 23:13

from django.db import migrations

# Dicionário com as regras de negócio que estavam no views.py
REGRAS_TECNICOS = {
    "Anderson Souza - NOC": [
        "Anderson Souza", "Anderson Souza - NOC", "Anderson Souza Gerdau Cearense",
        "Anderson Souza Gerdau Sapucaia", "Anderson Domingues - NOC", "Anderson Domingues Oliveira",
        "Anderson Oliveira"
    ],
    "Jair Equipe 3": ["Jair Equipe 3", "Jair Muhlbeier", "Jair/Rui - Equipe 3"],
    "André/Daniel Equipe Alphaville": [
        "Andre Darós", "Andre Rodrigo Farinhas Daros CPF:03188419082", "Andre daros",
        "André/Daniel Equipe Alphaville", "André/Lucas - Equipe Alphaville",
        "André/Nimay - Equipe Alphaville", "Andre Cunha"
    ],
    "Claudio BUS - Cosigua": ["Wellington/Claudio BUS - Cosigua", "Claudio BUS - Cosigua"],
    "Agnaldo - Equipe Shopping": [
        "Agnaldo - Equipe Shopping", "Agnaldo Santos", "Agnaldo/Felipe - Equipe Shopping"
    ],
    "Alcides Junior - Equipe Aço Norte": [
        "Alcides Junior", "Alcides Junior Gerdau Aço Norte", "Alcides/Marcelo - Equipe Aço Norte", "Edilson Junior", "Alcides  Junior"
    ],
    "Alex Romanato - Equipe Charqueadas": [
        "Alex Romanato", "Alex Romanato Gerdau Charqueadas", "Alex/Ygor - Equipe Charqueadas"
    ],
    "Augusto Brum - Equipe 1/Alfa": [
        "Augusto -  Equipe 1", "Augusto Brum", "Augusto Brum -  Equipe 1", "Augusto Santos de Brum CPF:03494672008",
        "Augusto Santos de Brum CPF:0394672008", "Augusto/Gustavo -  Equipe 1", "Augusto/Gustavo -  Equipe Alfa"
    ],
    "Reynaldo Conte - Lider Pinda/LiderSit": [
        "Reynaldo -  Equipe Pinda", "Reynaldo -  LiderSit", "Reynaldo Conde Gerdau Pinda", "Reynaldo Conte",
        "Reynaldo Supervisor", "Reynaldo. Conte", "Reynaldo/Brain LiderSit", "Reynaldo/Brian LiderSit",
        "Reynaldo/Luis Henrique LiderSit", "Reynaldo/Marcelo -  Equipe Pinda"
    ],
    "Vagner Costa - Equipe Divinópolis": [
        "Vagner - Equipe Divinópolis", "Vagner Costa", "Vagner Costa Equipe Divinópolis",
        "Vagner Costa Gitel Sede", "Vagner/ André - Equipe Divinópolis", "Vagner/ Igor - Equipe Divinópolis",
        "Vagner/Nathanael - Equipe Divinópolis"
    ],
    "Luis Gustavo - Equipe Pinda": [
        "Luis Gustavo  Equipe 2", "Luis Gustavo Gerdau Pinda", "Luis Gustavo Silva", "Luis Gustavo de Campos",
        "Luis/ Douglas -  Equipe Pinda 4", "Luis/Caio -  Equipe Pinda 2", "Luis/Itamar -  Equipe Pinda 2",
        "Luis/Marcelo -  Equipe Pinda 2", "Luiz Gustavo Medeiros da Silva CPF:676.007.860.87"
    ],
    "Julio Castro - Equipe Cearense": ["Julio Castro", "Julio Castro Gerdau Cearense", "julio castro"],
    "Eder - Equipe Mogi": ["Eder - Equipe Mogi", "Eder Henrique Pereira  Gerdau Mogi", "Eder/Alan - Equipe Mogi"],
    "Igor Ferreira - Equipe Cosigua 2": [
        "Igor  Ferreira", "Igor - Equipe Cosigua 2", "Igor / Gabriel  - Equipe Cosigua 2", "Igor Ferreira Gerdau GSP"
    ],
    "Marcelo - Equipe Pinda/Cosigua": [
        "Marcelo  Oliveira", "Marcelo Coelho", "Marcelo Oliveira Gerdau Recife", "Marcelo Rojo CSN Congonhas CFTV",
        "Marcelo/Breno -  Equipe Pinda 3", "Marcelo/Brian Equipe Pinda 3", "Marcelo/Hayan -  Equipe Pinda 3",
        "Marcelo/Luis Henrique Equipe Pinda 3", "Luis/Marcelo -  Equipe cosigua"
    ],
    "Caio - Equipe Pinda": [
        "Caio Raybbot Gerdau Pinda", "Caio/Breno -  Equipe Pinda 3", "Caio/Hayan -  Equipe Pinda 3",
        "Caio/Itamar -  Equipe Pinda 3"
    ],
    "Francisco - Equipe Cearense": [
        "Francisco -  Equipe Cearense", "Francisco Freitas Gerdau Cearense", "Francisco/ Allysson -  Equipe Cearense"
    ],
    "Ricardo - Equipe GSP": ["Ricardo Sousa Gerdau GSP", "Ricardo/Joelson -  Equipe GSP", "Ricardo/Tiago -  Equipe GSP"],
    "Leonardo César - CSN": ["Leonardo César", "Leonardo César  CSN Itaguaí"],
    "Wilsen Tony Pereira - Pinda": ["Wilsen Tony Pereira", "Wilsen Tony Pereira Gerdau Pinda"],
    "Eider Bottcher Coelho": ["Eider  Bottcher Coelho", "Eider Bottcher Coelho", "Eider Bottcher Coelho Projeto Gerdau"],
}

def forwards_func(apps, schema_editor):
    """Função que será executada ao aplicar a migração."""
    Tecnico = apps.get_model('Relatorio', 'Tecnico')
    MapeamentoTecnico = apps.get_model('Relatorio', 'MapeamentoTecnico')

    for nome_correto, nomes_errados in REGRAS_TECNICOS.items():
        # Cria ou obtém o registro do técnico com o nome correto
        tecnico_obj, created = Tecnico.objects.get_or_create(nome_correto=nome_correto)

        # Para cada nome errado, cria o mapeamento correspondente
        for nome_errado in nomes_errados:
            MapeamentoTecnico.objects.get_or_create(
                nome_incorreto=nome_errado,
                defaults={'tecnico_correto': tecnico_obj}
            )

def reverse_func(apps, schema_editor):
    """Função que será executada ao reverter a migração (desfazer)."""
    Tecnico = apps.get_model('Relatorio', 'Tecnico')
    MapeamentoTecnico = apps.get_model('Relatorio', 'MapeamentoTecnico')
    
    # Simplesmente deleta todos os registros criados
    MapeamentoTecnico.objects.all().delete()
    Tecnico.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0012_tecnico_mapeamentotecnico'), # Dependência corrigida!
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
