# Generated by Django 5.0.7 on 2025-10-18 12:58

from django.db import migrations

# Lista de regras corrigida e validada para evitar mapeamentos cruzados
REGRAS_TECNICOS_CORRIGIDAS = {
    # GRUPOS "ANDERSON" SEPARADOS
    "Anderson Souza - NOC": [
        "Anderson  Souza",
        "Anderson Souza -  NOC",
        "Anderson Souza Gerdau Cearense",
        "Anderson Souza Gerdau Sapucaia",
        "Anderson Souza",
    ],
    "Anderson Domingues - NOC": [
        "Anderson Domingues -   NOC",
        "Anderson Domingues Oliveira",
    ],
    "Anderson Oliveira": [
        "Anderson Oliveira",
    ],
    # GRUPO JAIR
    "Jair Equipe 3": [
        "Jair Equipe 3",
        "Jair Muhlbeier",
        "Jair/Rui - Equipe 3",
    ],
    # GRUPO ANDRÉ
    "André/Daniel Equipe Alphaville": [
        "Andre  Cunha",
        "Andre Darós",
        "Andre Rodrigo Farinhas Daros CPF:03188419082",
        "Andre daros",
        "André/Daniel  Equipe Alphaville",
        "André/Lucas -  Equipe Alphaville",
        "André/Nimay -  Equipe Alphaville",
    ],
    # DEMAIS GRUPOS
    "Agnaldo - Equipe Shopping": ["Agnaldo - Equipe Shopping", "Agnaldo Santos", "Agnaldo/Felipe - Equipe Shopping"],
    "Alcides Junior - Equipe Aço Norte": ["Alcides  Junior", "Alcides Junior Gerdau Aço Norte", "Alcides/Marcelo - Equipe Aço Norte", "Edilson  Junior"],
    "Alex Romanato - Equipe Charqueadas": ["Alex Romanato", "Alex Romanato Gerdau Charqueadas", "Alex/Ygor - Equipe Charqueadas"],
    "Augusto Brum - Equipe 1/Alfa": ["Augusto -  Equipe 1", "Augusto Brum", "Augusto Brum -  Equipe 1", "Augusto Santos de Brum CPF:03494672008", "Augusto Santos de Brum CPF:0394672008", "Augusto/Gustavo -  Equipe 1", "Augusto/Gustavo -  Equipe Alfa"],
    "Caio - Equipe Pinda": ["Caio Raybbot Gerdau Pinda", "Caio/Breno -  Equipe Pinda 3", "Caio/Hayan -  Equipe Pinda 3", "Caio/Itamar -  Equipe Pinda 3"],
    "Claudio BUS - Cosigua": ["Claudio BUS - Cosigua", "Wellington/Claudio BUS - Cosigua"],
    "Eder - Equipe Mogi": ["Eder - Equipe Mogi", "Eder Henrique Pereira  Gerdau Mogi", "Eder/Alan - Equipe Mogi"],
    "Eider Bottcher Coelho": ["Eider  Bottcher Coelho", "Eider Bottcher Coelho", "Eider Bottcher Coelho Projeto Gerdau"],
    "Francisco - Equipe Cearense": ["Francisco -  Equipe Cearense", "Francisco Freitas Gerdau Cearense", "Francisco/ Allysson -  Equipe Cearense"],
    "Igor Ferreira - Equipe Cosigua 2": ["Igor  Ferreira", "Igor - Equipe Cosigua 2", "Igor / Gabriel  - Equipe Cosigua 2", "Igor Ferreira Gerdau GSP"],
    "Julio Castro - Equipe Cearense": ["Julio Castro", "Julio Castro Gerdau Cearense", "julio castro"],
    "Leonardo César - CSN": ["Leonardo César", "Leonardo César  CSN Itaguaí"],
    "Luis Gustavo - Equipe Pinda": ["Luis Gustavo  Equipe 2", "Luis Gustavo Gerdau Pinda", "Luis Gustavo Silva", "Luis Gustavo de Campos", "Luis/ Douglas -  Equipe Pinda 4", "Luis/Caio -  Equipe Pinda 2", "Luis/Itamar -  Equipe Pinda 2", "Luis/Marcelo -  Equipe Pinda 2", "Luiz Gustavo Medeiros da Silva CPF:676.007.860.87"],
    "Marcelo - Equipe Pinda/Cosigua": ["Luis/Marcelo -  Equipe cosigua", "Marcelo  Oliveira", "Marcelo Coelho", "Marcelo Oliveira Gerdau Recife", "Marcelo Rojo CSN Congonhas CFTV", "Marcelo/Breno -  Equipe Pinda 3", "Marcelo/Brian Equipe Pinda 3", "Marcelo/Hayan -  Equipe Pinda 3", "Marcelo/Luis Henrique Equipe Pinda 3"],
    "Reynaldo Conte - Lider Pinda/LiderSit": ["Reynaldo -  Equipe Pinda", "Reynaldo -  LiderSit", "Reynaldo Conde Gerdau Pinda", "Reynaldo Conte", "Reynaldo Supervisor", "Reynaldo. Conte", "Reynaldo/Brain LiderSit", "Reynaldo/Brian LiderSit", "Reynaldo/Luis Henrique LiderSit", "Reynaldo/Marcelo -  Equipe Pinda"],
    "Ricardo - Equipe GSP": ["Ricardo Sousa Gerdau GSP", "Ricardo/Joelson -  Equipe GSP", "Ricardo/Tiago -  Equipe GSP"],
    "Vagner Costa - Equipe Divinópolis": ["Vagner - Equipe Divinópolis", "Vagner Costa", "Vagner Costa Equipe Divinópolis", "Vagner Costa Gitel Sede", "Vagner/ André - Equipe Divinópolis", "Vagner/ Igor - Equipe Divinópolis", "Vagner/Nathanael - Equipe Divinópolis"],
    "Wilsen Tony Pereira - Pinda": ["Wilsen Tony Pereira", "Wilsen Tony Pereira Gerdau Pinda"],
}

def forwards_func(apps, schema_editor):
    """Limpa os dados antigos e popula com as regras corrigidas."""
    Tecnico = apps.get_model('Relatorio', 'Tecnico')
    MapeamentoTecnico = apps.get_model('Relatorio', 'MapeamentoTecnico')

    # 1. Limpa completamente as tabelas para recomeçar
    MapeamentoTecnico.objects.all().delete()
    Tecnico.objects.all().delete()

    # 2. Popula as tabelas com os dados corrigidos
    for nome_correto, nomes_errados in REGRAS_TECNICOS_CORRIGIDAS.items():
        tecnico_obj, created = Tecnico.objects.get_or_create(nome_correto=nome_correto)
        for nome_errado in nomes_errados:
            MapeamentoTecnico.objects.get_or_create(
                nome_incorreto=nome_errado,
                defaults={'tecnico_correto': tecnico_obj}
            )

def reverse_func(apps, schema_editor):
    """Função de reversão: simplesmente apaga os dados criados."""
    Tecnico = apps.get_model('Relatorio', 'Tecnico')
    MapeamentoTecnico = apps.get_model('Relatorio', 'MapeamentoTecnico')
    MapeamentoTecnico.objects.all().delete()
    Tecnico.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0013_auto_20251017_2313'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
