# Generated by Django 5.2.7 on 2025-10-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0014_auto_20251018_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapeamentoTecnico',
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
