# Generated by Django 5.2.7 on 2025-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS', models.CharField(max_length=50, unique=True, verbose_name='OS')),
                ('Status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('Nivel_de_Criticidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível de Criticidade')),
                ('Avanco_da_OS', models.IntegerField(blank=True, null=True, verbose_name='Avanço da OS (%)')),
                ('Criado_Por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Criado Por')),
                ('Responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('Ativo', models.TextField(blank=True, null=True, verbose_name='Ativo')),
                ('Plano_de_Tarefas', models.TextField(blank=True, null=True, verbose_name='Plano de Tarefas')),
                ('Tipo_de_Tarefa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Tarefa')),
                ('Duracao_Minutos', models.FloatField(blank=True, null=True, verbose_name='Duração (Minutos)')),
                ('Data_Criacao_OS', models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação OS')),
                ('Ano_Criacao', models.IntegerField(blank=True, null=True)),
                ('Mes_Criacao', models.IntegerField(blank=True, null=True)),
                ('Dia_Criacao', models.IntegerField(blank=True, null=True)),
                ('Hora_Criacao', models.TimeField(blank=True, null=True)),
                ('Data_Finalizacao_OS', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização OS')),
                ('Ano_Finalizacao', models.IntegerField(blank=True, null=True)),
                ('Mes_Finalizacao', models.IntegerField(blank=True, null=True)),
                ('Dia_Finalizacao', models.IntegerField(blank=True, null=True)),
                ('Hora_Finalizacao', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
