# Generated by Django 5.2.7 on 2025-10-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0002_remove_ordemdeservico_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='Status_da_Tarefa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da Tarefa'),
        ),
    ]
