# Generated by Django 5.2.7 on 2025-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0003_tarefa_status_da_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='Avanco_da_OS',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Avanco_da_OS',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avanço da OS (%)'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Local_Empresa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local/Empresa'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Possui_Ticket',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Possui Ticket?'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='Ticket_ID',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Ticket'),
        ),
    ]
