# Generated by Django 5.2.7 on 2025-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0005_ordemdeservico_ano_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='Observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
