# Generated by Django 5.2.7 on 2025-10-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0006_tarefa_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='Observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
