# Generated by Django 5.2.7 on 2025-10-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0008_transferir_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='Observacao',
        ),
    ]
