# Generated by Django 5.2.7 on 2025-10-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0011_ordemdeservico_data_enviado_verificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_correto', models.CharField(max_length=255, unique=True, verbose_name='Nome Correto do Técnico')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['nome_correto'],
            },
        ),
        migrations.CreateModel(
            name='MapeamentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_incorreto', models.CharField(max_length=255, unique=True, verbose_name='Nome Incorreto (como vem do sistema)')),
                ('tecnico_correto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='Relatorio.tecnico')),
            ],
            options={
                'verbose_name': 'Mapeamento de Técnico',
                'verbose_name_plural': 'Mapeamentos de Técnicos',
                'ordering': ['nome_incorreto'],
            },
        ),
    ]
