# Generated by Django 5.2.7 on 2025-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=True, verbose_name='Obrigar Troca de Senha'),
        ),
    ]
