# Generated by Django 5.2.7 on 2025-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0017_alter_profile_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='Local_Agrupado',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Cliente (Agrupado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='Responsavel_Agrupado',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Responsável (Grupo)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='Tipo_Tarefa_Agrupado',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tipo de Tarefa (Grupo)'),
        ),
    ]
