# Generated by Django 5.2.7 on 2025-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0018_ordemdeservico_local_agrupado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='Local_Detalhado',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Local Detalhado'),
        ),
    ]
