# Generated by Django 5.2.7 on 2026-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0019_ordemdeservico_local_detalhado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feacsg',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'feacsg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feadiv',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'feadiv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feagsp',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'feagsp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='L1Pinda',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'l1pinda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lam2Csg',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lam2csg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lw01Pinda',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lw01pinda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puccsg',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'puccsg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shrcsg',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'shrcsg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shrgsp',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('startdate', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'shrgsp',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='causes_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Causa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='detection_method_description',
            field=models.TextField(blank=True, null=True, verbose_name='Método de Detecção'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='types_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Tipo'),
        ),
    ]
