# Generated by Django 5.2.7 on 2026-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0020_feacsg_feadiv_feagsp_l1pinda_lam2csg_lw01pinda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='Custo_Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total (R$)'),
        ),
    ]
